include $(THEOS)/makefiles/common.mk

BUNDLE_NAME = VinylPrefs

VinylPrefs_FILES = VinylRootListController.m
VinylPrefs_INSTALL_PATH = /Library/PreferenceBundles
VinylPrefs_FRAMEWORKS = UIKit
VinylPrefs_PRIVATE_FRAMEWORKS = Preferences
VinylPrefs_CFLAGS = -fobjc-arc

include $(THEOS_MAKE_PATH)/bundle.mk
